### ISSUE TITLE
Hamburger button is overlapped at bottom.

### ISSUE THREAD

**Issue by 532910** [AsteroidOS/asteroidos.org#8] opened 2018-04-11 15:26 UTC
![asteroid_hamburger](https://user-images.githubusercontent.com/14617699/38626661-bea18678-3db5-11e8-9222-2765ad611ee5.png)

**Comment by c-e-p-x-u-o** [comment] 2018-04-12 15:46
I can reproduce this issue with any browser. OK, it's really not 'bottom overlapped', but 'improperly scaled'. Just try to scale. Looks like it's due to three independent spans. Could you make it SVG also?

**Comment by c-e-p-x-u-o** [comment] 2018-04-12 15:53
There is also &#9776; unicode character, but it's ugly and may not work for all.
Possible it's better to use character with specified web font.

**Comment by eLtMosen** [comment] 2023-03-14 14:51
Having looked into this quite often now during development of the site. I could never reproduce it in 2022 and 2023.
Closing this for peace of mind. The issue might just have fixed itself over browser generations.
Feel free to open again if this is wrong.
I'd be happy to work on actually solving the issue if i could reproduce it.

**Closed by eLtMosen** 2023-03-14 14:52 UTC
